# prettier-ignore

version: "3.9"

networks:
  web:
    name: web
    external: false
  internal:
    name: internal
    external: false

services:
  nginx:
    image: nginx:latest
    profiles: ["server"]
    depends_on:
      - api
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # traefik:
  #   image: traefik
  #   profiles: ["server", "traefik"]
  #   restart: always
  #   labels:
  #     - traefik.enable=false
  #   networks:
  #     - internal
  #     - web
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 8080:8080
  #   volumes:
  #     - ./devops:/etc/traefik
  #     - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    profiles: ["server", "api"]
    restart: always
    labels:
      - traefik.http.routers.ordit.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.port=80
    env_file:
      - .env
    networks:
      - internal
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: ${API_REPLICAS}
      restart_policy:
        max_attempts: 3
        condition: on-failure
    command: npm start

  bitcoin:
    image: ruimarinho/bitcoin-core
    profiles: ["local", "bitcoin"]
    restart: always
    labels:
      - traefik.enable=false
    ports:
      - ${RPC_PORT}:${RPC_PORT} # regtest:18443 testnet:18332 mainnet:8332
    volumes:
      - ./.data/bitcoin:/home/bitcoin/.bitcoin
    networks:
      - internal
    command:
      -printtoconsole
      -txindex=1
      -${NETWORK}=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -blocknotify='curl ${RPC_NOTIFY}/hooks/bitcoin?block=%s'

  mongodb:
    image: mongo:latest
    profiles: ["local", "db", "mongodb"]
    restart: always
    labels:
      - traefik.enable=false
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - internal
    volumes:
      - ./.data/mongodb:/data/db
