# prettier-ignore

version: "3.9"

networks:
  web:
    name: web
    external: false
  internal:
    name: internal
    external: false

services:
  api:
    build: .
    profiles: ["server", "api"]
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal
      - web
    deploy:
      replicas: ${API_REPLICAS}
      restart_policy:
        max_attempts: 3
        condition: on-failure
    command: npm start

  nginx:
    image: nginx:latest
    profiles: ["server", "api"]
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    depends_on:
      - api
    networks:
      - internal
      - web
    ports:
      - ${API_PORT}:${API_PORT}
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  bitcoin:
    image: ruimarinho/bitcoin-core
    profiles: ["local", "bitcoin"]
    restart: unless-stopped
    labels:
      - traefik.enable=false
    ports:
      - ${RPC_PORT}:${RPC_PORT} # regtest:18443 testnet:18332 signet:38332 mainnet:8332
    volumes:
      - ./.data/bitcoin:/home/bitcoin/.bitcoin
    networks:
      - internal
    command:
      -printtoconsole
      -txindex=1
      -${NETWORK}=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -blocknotify='curl ${RPC_NOTIFY}/hooks/bitcoin?block=%s'

  mongodb:
    image: mongo:latest
    profiles: ["local", "db", "mongodb"]
    restart: unless-stopped
    labels:
      - traefik.enable=false
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - internal
    volumes:
      - ./.data/mongodb:/data/db
