version: "3.8"

services:
  bitcoin:
    image: ruimarinho/bitcoin-core
    restart: always
    ports:
      - 18332:18332 # regtest:18443 testnet:18332 mainnet:8332
    volumes:
      - ./.bitcoin:/home/bitcoin/.bitcoin
    command: 
      -printtoconsole
      -txindex=1
      -testnet=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -blocknotify='curl http://host.docker.internal:3031/hooks/bitcoin?block=%s' # target trinity watcher
